---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  default_box: generic/rocky9
platforms:
  - name: haproxy
    memory: 2048
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible


